### PR TITLE
Remove coupon error

### PR DESCRIPTION
**Pull request by diegoleone**
When a coupon that triggers a campaign promotion (created within the campaign audience) is used in the checkout, it modifies the price correctly but displays an error message as if there was no promotion linked to it. 

This PR removes the error by checking if the coupon is present in the `orderForm.ratesAndBenefitsData.ratesAndBenefitsIdentifiers`

Test in: https://testleone--arcaplanetqa.myvtex.com

### CODE REVIEW

**Comment by Fbenitez97** [comment]
@polishq do you think we can have this PR merge into master?

**Comment by polishq** [comment]
@diegoleone Please follow the instructions in the `For VTEX Developers` section of the readme. The checkout JS needs to be recompiled when making this type of change.

**Comment by albertm805** [comment]
@Fbenitez97 Can you run `yarn run build` please? This needs to be run in the `checkout-ui-custom` folder.

**Comment by beatrizmaselli** [comment]
Closing this PR. Done here the adjustment: https://github.com/vtex-apps/checkout-ui-custom/pull/204

**Pull request closed without merging**
